import { Roboto, IBM_Plex_Sans } from "next/font/google";
import Navbar from "components/blocks/Navbar";
import StyledComponentsRegistry from "utils/registry";
import { GlobalStyle } from "styles/GlobalStyle";
import "bootstrap/dist/css/bootstrap.css";
import Footer from "components/blocks/Footer";

const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

const ibm = IBM_Plex_Sans({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-ibm",
  display: "swap",
});

export const metadata = {
  title: "Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${ibm.variable}`}
        suppressHydrationWarning={true}
      >
        <StyledComponentsRegistry>
          <GlobalStyle />
          <Navbar />
          {children}
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
